server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fuel_order_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: FuelHikariPool
      minimum-idle: 5
      maximum-pool-size: 10
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 60000
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  jwt-secret: ${JWT_SECRET:3b1b9d12f7b8a4f9c48e94a1cb4a6b847c42b3e01c5975c8c4b3f1a73d32a9b1}
  token-ttl: 86400000

logging:
  level:
    root: INFO
#    org.springframework: DEBUG